const events = {
    AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
    AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
    USER_UPDATED: "USER_UPDATED",
    DISPLAY_MESSAGE: "DISPLAY_MESSAGE"
};

export default events;
